basePath: /
definitions:
  models.Address:
    properties:
      detailaddress:
        type: string
      district:
        type: string
      fullname:
        type: string
      id:
        type: integer
      phone:
        type: string
      province:
        type: string
      typeaddress:
        type: boolean
      user_id:
        description: Khóa ngoại trỏ đến user
        type: integer
      village:
        type: string
    type: object
  models.User:
    properties:
      addresses:
        description: 'Quan hệ 1-nhiều: 1 user có nhiều địa chỉ'
        items:
          $ref: '#/definitions/models.Address'
        type: array
      dob:
        type: string
      email:
        type: string
      fullname:
        type: string
      gender:
        type: string
      id:
        type: integer
      password:
        type: string
      phone:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  request.AddressRequest:
    properties:
      detailaddress:
        type: string
      district:
        type: string
      fullname:
        type: string
      phone:
        type: string
      province:
        type: string
      typeaddress:
        type: boolean
      village:
        type: string
    type: object
  request.CategoryRequest:
    properties:
      image_url:
        type: string
      name:
        type: string
    required:
    - image_url
    - name
    type: object
  request.CreateUserRequest:
    properties:
      dob:
        type: string
      email:
        type: string
      fullname:
        maxLength: 50
        minLength: 2
        type: string
      gender:
        type: string
      password:
        minLength: 6
        type: string
      phone:
        type: string
      username:
        minLength: 3
        type: string
    required:
    - email
    - fullname
    - gender
    - password
    - phone
    - username
    type: object
  request.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  request.LogoutRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  response.AddressResponse:
    properties:
      detailaddress:
        type: string
      district:
        type: string
      fullname:
        type: string
      id:
        type: integer
      phone:
        type: string
      province:
        type: string
      typeaddress:
        type: boolean
      user_id:
        description: Khóa ngoại trỏ đến user
        type: integer
      village:
        type: string
    type: object
  response.ApiResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  response.CategoryResponse:
    properties:
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      path:
        type: string
    type: object
  response.UserResponse:
    properties:
      dob:
        type: string
      email:
        type: string
      fullname:
        type: string
      gender:
        type: string
      id:
        type: integer
      phone:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: duy@example.com
    name: Duy
    url: http://github.com/daoduy
  description: Đây là tài liệu API cho project học Golang
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Học Golang API
  version: "1.0"
paths:
  /address/add:
    post:
      consumes:
      - application/json
      description: Người dùng có thể thêm địa chỉ mới dựa trên token JWT
      parameters:
      - description: Thông tin địa chỉ
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.AddressRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AddressResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Thêm địa chỉ mới cho người dùng hiện tại
      tags:
      - Address
  /address/myaddress:
    get:
      description: Lấy danh sách tất cả địa chỉ của người dùng dựa trên token JWT
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.AddressResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Lấy danh sách địa chỉ người dùng hiện tại
      tags:
      - Address
  /address/update/{id}:
    put:
      consumes:
      - application/json
      description: Người dùng có thể cập nhật địa chỉ hiện tại dựa trên token JWT
      parameters:
      - description: ID của địa chỉ
        in: path
        name: id
        required: true
        type: string
      - description: Thông tin địa chỉ
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.AddressRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AddressResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Cập nhật địa chỉ hiện tại của người dùng
      tags:
      - Address
  /auth/login:
    post:
      consumes:
      - application/json
      description: Cho phép người dùng đăng nhập bằng username và password
      parameters:
      - description: Thông tin đăng nhập
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Đăng nhập
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Thêm token vào danh sách vô hiệu hoá
      parameters:
      - description: Token cần vô hiệu hoá
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Đăng xuất người dùng
      tags:
      - Auth
  /categories/:
    get:
      description: Lấy danh sách tất cả danh mục
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.CategoryResponse'
            type: array
      summary: Lấy danh sách tất cả danh mục
      tags:
      - Category
    post:
      consumes:
      - application/json
      description: Tạo danh mục
      parameters:
      - description: Thông tin danh mục
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CategoryResponse'
      summary: Tạo danh mục
      tags:
      - Category
  /categories/{path}:
    get:
      description: Lấy danh mục theo path
      parameters:
      - description: Path của danh mục
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CategoryResponse'
      summary: Lấy danh mục theo path
      tags:
      - Category
  /users/:
    get:
      description: Trả về danh sách user trong hệ thống
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Lấy danh sách tất cả người dùng
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Tạo mới một người dùng trong hệ thống
      parameters:
      - description: Thông tin tạo người dùng
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Tạo mới người dùng
      tags:
      - User
  /users/{id}:
    get:
      description: Trả về thông tin chi tiết của người dùng theo ID
      parameters:
      - description: ID của người dùng
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
      summary: Lấy thông tin người dùng theo ID
      tags:
      - User
  /users/myinfo:
    get:
      description: Lấy thông tin người dùng từ token JWT
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Lấy thông tin người dùng hiện tại
      tags:
      - User
security:
- BearerAuth: []
securityDefinitions:
  BearerAuth:
    description: 'Nhập token theo định dạng: Bearer <your_token>'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
